### ISSUE TITLE
[TODO] Recursive mask

### ISSUE THREAD

**Issue by denji** [sschober/kqwait#3]
- [ ] `*` watch level 1 structure _(current: not working)_<br>
  Example: /var/www/site1/_/ or /var/www/site1/_
- [ ] `/**/` watch recursive subfolder, level **∞** _(current: not working)_<br>
  Example: /var/www/site1/**/

**Comment by jskopek** [comment]
Does kqwait have the ability to watch recursive subfolders? I'm finding it to be increasingly invaluable, but  having to manually define which files I need to watch accross larger projects becomes very time consuming. A feature like this - if it exists - would be incredible for my workflow
